cadence:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'  
      server:   HOMEDESKTOP-MAR# Replace with your SQL Server name
      database: cadence  
      schema: dbo  
      trusted_connection: yes  
      trust_cert: true
      port: 1433  